<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('jo_profile', 'jo_profile_packet_id_jo_profile_packet_id', array(
             'name' => 'jo_profile_packet_id_jo_profile_packet_id',
             'local' => 'packet_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_profile_packet',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_profile_packet_translation', 'jo_profile_packet_translation_id_jo_profile_packet_id', array(
             'name' => 'jo_profile_packet_translation_id_jo_profile_packet_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_profile_packet',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('jo_profile', 'jo_profile_packet_id', array(
             'fields' => 
             array(
              0 => 'packet_id',
             ),
             ));
        $this->addIndex('jo_profile_packet_translation', 'jo_profile_packet_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('jo_profile', 'jo_profile_packet_id_jo_profile_packet_id');
        $this->dropForeignKey('jo_profile_packet_translation', 'jo_profile_packet_translation_id_jo_profile_packet_id');
        $this->removeIndex('jo_profile', 'jo_profile_packet_id', array(
             'fields' => 
             array(
              0 => 'packet_id',
             ),
             ));
        $this->removeIndex('jo_profile_packet_translation', 'jo_profile_packet_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}