<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('jo_billing', 'jo_billing_user_id_sf_guard_user_id', array(
             'name' => 'jo_billing_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_billing', 'jo_billing_type_id_jo_billing_type_id', array(
             'name' => 'jo_billing_type_id_jo_billing_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_billing_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_blacklist', 'jo_blacklist_user_id_sf_guard_user_id', array(
             'name' => 'jo_blacklist_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_blacklist', 'jo_blacklist_black_id_sf_guard_user_id', array(
             'name' => 'jo_blacklist_black_id_sf_guard_user_id',
             'local' => 'black_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_friend', 'jo_friend_user_id_sf_guard_user_id', array(
             'name' => 'jo_friend_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_friend', 'jo_friend_friend_id_sf_guard_user_id', array(
             'name' => 'jo_friend_friend_id_sf_guard_user_id',
             'local' => 'friend_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_friend', 'jo_friend_status_id_jo_status_friend_id', array(
             'name' => 'jo_friend_status_id_jo_status_friend_id',
             'local' => 'status_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_status_friend',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_hotlist', 'jo_hotlist_from_id_sf_guard_user_id', array(
             'name' => 'jo_hotlist_from_id_sf_guard_user_id',
             'local' => 'from_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_hotlist', 'jo_hotlist_to_id_sf_guard_user_id', array(
             'name' => 'jo_hotlist_to_id_sf_guard_user_id',
             'local' => 'to_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_hotlist', 'jo_hotlist_last_message_id_jo_message_id', array(
             'name' => 'jo_hotlist_last_message_id_jo_message_id',
             'local' => 'last_message_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_message',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_interest', 'jo_interest_user_id_sf_guard_user_id', array(
             'name' => 'jo_interest_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_interest', 'jo_interest_interest_id_sf_guard_user_id', array(
             'name' => 'jo_interest_interest_id_sf_guard_user_id',
             'local' => 'interest_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_message', 'jo_message_from_id_sf_guard_user_id', array(
             'name' => 'jo_message_from_id_sf_guard_user_id',
             'local' => 'from_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_message', 'jo_message_to_id_sf_guard_user_id', array(
             'name' => 'jo_message_to_id_sf_guard_user_id',
             'local' => 'to_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_payment', 'jo_payment_user_id_sf_guard_user_id', array(
             'name' => 'jo_payment_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_payment', 'jo_payment_partner_id_sf_guard_user_id', array(
             'name' => 'jo_payment_partner_id_sf_guard_user_id',
             'local' => 'partner_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_payment', 'jo_payment_woman_id_sf_guard_user_id', array(
             'name' => 'jo_payment_woman_id_sf_guard_user_id',
             'local' => 'woman_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_payment', 'jo_payment_service_id_jo_service_id', array(
             'name' => 'jo_payment_service_id_jo_service_id',
             'local' => 'service_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_service',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_photo', 'jo_photo_user_id_sf_guard_user_id', array(
             'name' => 'jo_photo_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_photo', 'jo_photo_partner_id_sf_guard_user_id', array(
             'name' => 'jo_photo_partner_id_sf_guard_user_id',
             'local' => 'partner_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_profile', 'jo_profile_user_id_sf_guard_user_id', array(
             'name' => 'jo_profile_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('jo_profile', 'jo_profile_status_id_jo_profile_type_id', array(
             'name' => 'jo_profile_status_id_jo_profile_type_id',
             'local' => 'status_id',
             'foreign' => 'id',
             'foreignTable' => 'jo_profile_type',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_video', 'jo_video_user_id_sf_guard_user_id', array(
             'name' => 'jo_video_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_video', 'jo_video_partner_id_sf_guard_user_id', array(
             'name' => 'jo_video_partner_id_sf_guard_user_id',
             'local' => 'partner_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_faq_translation', 'jo_faq_translation_id_jo_faq_id', array(
             'name' => 'jo_faq_translation_id_jo_faq_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_faq',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_news_translation', 'jo_news_translation_id_jo_news_id', array(
             'name' => 'jo_news_translation_id_jo_news_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_news',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_notify_translation', 'jo_notify_translation_id_jo_notify_id', array(
             'name' => 'jo_notify_translation_id_jo_notify_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_notify',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_page_translation', 'jo_page_translation_id_jo_page_id', array(
             'name' => 'jo_page_translation_id_jo_page_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_page',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_profile_type_translation', 'jo_profile_type_translation_id_jo_profile_type_id', array(
             'name' => 'jo_profile_type_translation_id_jo_profile_type_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_profile_type',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('jo_service_translation', 'jo_service_translation_id_jo_service_id', array(
             'name' => 'jo_service_translation_id_jo_service_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'jo_service',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('jo_billing', 'jo_billing_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_billing', 'jo_billing_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->addIndex('jo_blacklist', 'jo_blacklist_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_blacklist', 'jo_blacklist_black_id', array(
             'fields' => 
             array(
              0 => 'black_id',
             ),
             ));
        $this->addIndex('jo_friend', 'jo_friend_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_friend', 'jo_friend_friend_id', array(
             'fields' => 
             array(
              0 => 'friend_id',
             ),
             ));
        $this->addIndex('jo_friend', 'jo_friend_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
        $this->addIndex('jo_hotlist', 'jo_hotlist_from_id', array(
             'fields' => 
             array(
              0 => 'from_id',
             ),
             ));
        $this->addIndex('jo_hotlist', 'jo_hotlist_to_id', array(
             'fields' => 
             array(
              0 => 'to_id',
             ),
             ));
        $this->addIndex('jo_hotlist', 'jo_hotlist_last_message_id', array(
             'fields' => 
             array(
              0 => 'last_message_id',
             ),
             ));
        $this->addIndex('jo_interest', 'jo_interest_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_interest', 'jo_interest_interest_id', array(
             'fields' => 
             array(
              0 => 'interest_id',
             ),
             ));
        $this->addIndex('jo_message', 'jo_message_from_id', array(
             'fields' => 
             array(
              0 => 'from_id',
             ),
             ));
        $this->addIndex('jo_message', 'jo_message_to_id', array(
             'fields' => 
             array(
              0 => 'to_id',
             ),
             ));
        $this->addIndex('jo_payment', 'jo_payment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_payment', 'jo_payment_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->addIndex('jo_payment', 'jo_payment_woman_id', array(
             'fields' => 
             array(
              0 => 'woman_id',
             ),
             ));
        $this->addIndex('jo_payment', 'jo_payment_service_id', array(
             'fields' => 
             array(
              0 => 'service_id',
             ),
             ));
        $this->addIndex('jo_photo', 'jo_photo_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_photo', 'jo_photo_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->addIndex('jo_profile', 'jo_profile_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_profile', 'jo_profile_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
        $this->addIndex('jo_video', 'jo_video_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('jo_video', 'jo_video_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->addIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->addIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->addIndex('jo_faq_translation', 'jo_faq_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('jo_news_translation', 'jo_news_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('jo_notify_translation', 'jo_notify_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('jo_page_translation', 'jo_page_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('jo_profile_type_translation', 'jo_profile_type_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('jo_service_translation', 'jo_service_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('jo_billing', 'jo_billing_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_billing', 'jo_billing_type_id_jo_billing_type_id');
        $this->dropForeignKey('jo_blacklist', 'jo_blacklist_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_blacklist', 'jo_blacklist_black_id_sf_guard_user_id');
        $this->dropForeignKey('jo_friend', 'jo_friend_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_friend', 'jo_friend_friend_id_sf_guard_user_id');
        $this->dropForeignKey('jo_friend', 'jo_friend_status_id_jo_status_friend_id');
        $this->dropForeignKey('jo_hotlist', 'jo_hotlist_from_id_sf_guard_user_id');
        $this->dropForeignKey('jo_hotlist', 'jo_hotlist_to_id_sf_guard_user_id');
        $this->dropForeignKey('jo_hotlist', 'jo_hotlist_last_message_id_jo_message_id');
        $this->dropForeignKey('jo_interest', 'jo_interest_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_interest', 'jo_interest_interest_id_sf_guard_user_id');
        $this->dropForeignKey('jo_message', 'jo_message_from_id_sf_guard_user_id');
        $this->dropForeignKey('jo_message', 'jo_message_to_id_sf_guard_user_id');
        $this->dropForeignKey('jo_payment', 'jo_payment_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_payment', 'jo_payment_partner_id_sf_guard_user_id');
        $this->dropForeignKey('jo_payment', 'jo_payment_woman_id_sf_guard_user_id');
        $this->dropForeignKey('jo_payment', 'jo_payment_service_id_jo_service_id');
        $this->dropForeignKey('jo_photo', 'jo_photo_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_photo', 'jo_photo_partner_id_sf_guard_user_id');
        $this->dropForeignKey('jo_profile', 'jo_profile_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_profile', 'jo_profile_status_id_jo_profile_type_id');
        $this->dropForeignKey('jo_video', 'jo_video_user_id_sf_guard_user_id');
        $this->dropForeignKey('jo_video', 'jo_video_partner_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('jo_faq_translation', 'jo_faq_translation_id_jo_faq_id');
        $this->dropForeignKey('jo_news_translation', 'jo_news_translation_id_jo_news_id');
        $this->dropForeignKey('jo_notify_translation', 'jo_notify_translation_id_jo_notify_id');
        $this->dropForeignKey('jo_page_translation', 'jo_page_translation_id_jo_page_id');
        $this->dropForeignKey('jo_profile_type_translation', 'jo_profile_type_translation_id_jo_profile_type_id');
        $this->dropForeignKey('jo_service_translation', 'jo_service_translation_id_jo_service_id');
        $this->removeIndex('jo_billing', 'jo_billing_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_billing', 'jo_billing_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->removeIndex('jo_blacklist', 'jo_blacklist_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_blacklist', 'jo_blacklist_black_id', array(
             'fields' => 
             array(
              0 => 'black_id',
             ),
             ));
        $this->removeIndex('jo_friend', 'jo_friend_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_friend', 'jo_friend_friend_id', array(
             'fields' => 
             array(
              0 => 'friend_id',
             ),
             ));
        $this->removeIndex('jo_friend', 'jo_friend_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
        $this->removeIndex('jo_hotlist', 'jo_hotlist_from_id', array(
             'fields' => 
             array(
              0 => 'from_id',
             ),
             ));
        $this->removeIndex('jo_hotlist', 'jo_hotlist_to_id', array(
             'fields' => 
             array(
              0 => 'to_id',
             ),
             ));
        $this->removeIndex('jo_hotlist', 'jo_hotlist_last_message_id', array(
             'fields' => 
             array(
              0 => 'last_message_id',
             ),
             ));
        $this->removeIndex('jo_interest', 'jo_interest_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_interest', 'jo_interest_interest_id', array(
             'fields' => 
             array(
              0 => 'interest_id',
             ),
             ));
        $this->removeIndex('jo_message', 'jo_message_from_id', array(
             'fields' => 
             array(
              0 => 'from_id',
             ),
             ));
        $this->removeIndex('jo_message', 'jo_message_to_id', array(
             'fields' => 
             array(
              0 => 'to_id',
             ),
             ));
        $this->removeIndex('jo_payment', 'jo_payment_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_payment', 'jo_payment_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->removeIndex('jo_payment', 'jo_payment_woman_id', array(
             'fields' => 
             array(
              0 => 'woman_id',
             ),
             ));
        $this->removeIndex('jo_payment', 'jo_payment_service_id', array(
             'fields' => 
             array(
              0 => 'service_id',
             ),
             ));
        $this->removeIndex('jo_photo', 'jo_photo_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_photo', 'jo_photo_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->removeIndex('jo_profile', 'jo_profile_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_profile', 'jo_profile_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
        $this->removeIndex('jo_video', 'jo_video_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('jo_video', 'jo_video_partner_id', array(
             'fields' => 
             array(
              0 => 'partner_id',
             ),
             ));
        $this->removeIndex('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_group_permission', 'sf_guard_group_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->removeIndex('sf_guard_remember_key', 'sf_guard_remember_key_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_group', 'sf_guard_user_group_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('sf_guard_user_permission', 'sf_guard_user_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
        $this->removeIndex('jo_faq_translation', 'jo_faq_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('jo_news_translation', 'jo_news_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('jo_notify_translation', 'jo_notify_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('jo_page_translation', 'jo_page_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('jo_profile_type_translation', 'jo_profile_type_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('jo_service_translation', 'jo_service_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}