<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('jo_billing', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'summa' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'balance' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'credit' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'type_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_billing_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'summa' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'credit' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_blacklist', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'black_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_faq', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_friend', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'friend_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'status_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'del_user' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'del_friend' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_read_user' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_read_friend' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'contact' => 
             array(
              'type' => 'string',
              'length' => '10000',
             ),
             'from_partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'to_partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'request_video' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'accept_video' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'read_accept' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'is_read_user' => 
              array(
              'fields' => 
              array(
               0 => 'is_read_user',
              ),
              ),
              'is_read_friend' => 
              array(
              'fields' => 
              array(
               0 => 'is_read_friend',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_hotlist', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'from_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'to_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'last_message_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'is_new_message' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_opened' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_interest', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'interest_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'is_read_user' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_read_interest' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_message', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'from_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'from_username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'to_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'to_username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'from_partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'to_partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'translate' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'reply_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'type_message' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'smile',
              1 => 'message',
              2 => 'first',
              ),
              'default' => 'message',
              'length' => '',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'true',
              'length' => '25',
             ),
             'is_read' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_reply' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'del_from' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'del_to' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'to_username' => 
              array(
              'fields' => 
              array(
               0 => 'to_username',
              ),
              ),
              'from_username' => 
              array(
              'fields' => 
              array(
               0 => 'from_username',
              ),
              ),
              'reply_id' => 
              array(
              'fields' => 
              array(
               0 => 'reply_id',
              ),
              ),
              'type_message' => 
              array(
              'fields' => 
              array(
               0 => 'type_message',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_news', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_notify', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_page', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'alias' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'undel' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_payment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'service_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'woman_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'room_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'summa' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'balanse' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'comission' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'cost' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'is_closed' => 
             array(
              'type' => 'boolean',
              'default' => 'true',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_photo', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_main' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_private' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'size' => 
             array(
              'type' => 'integer',
              'length' => '11',
             ),
             'partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'middle_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'real_name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'gender' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'm',
              1 => 'w',
              ),
              'default' => 'w',
              'length' => '',
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'country' => 
             array(
              'type' => 'string',
              'length' => '2',
             ),
             'zip' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'adress' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'birthday' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'height' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'body_type' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'relationship' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'rost' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'ves' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'ethnicity' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'religion' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'marital_status' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'children' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'where_children' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'want_children' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'im' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'occupation' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'language1' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'language_skill1' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'language2' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'language_skill2' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'language3' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'language_skill3' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'education' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'income' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'smoker' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'drinker' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'headline' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '25000',
             ),
             'i_can_receive' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'i_look_for_a' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'looking_for_age_from' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'looking_for_age_to' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'looking_for_a_height_from' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'looking_for_a_height_to' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'looking_for_a_body_type_from' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'looking_for_a_body_type_to' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'ideal_match_description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'notify_me_about_news' => 
             array(
              'type' => 'boolean',
              'default' => 'true',
              'length' => '25',
             ),
             'mobile_phone' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'photo' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_new_message' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_new_friend' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_new_request' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_new_gift' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_new_hotlist' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_empty' => 
             array(
              'type' => 'boolean',
              'default' => 'true',
              'length' => '25',
             ),
             'is_online' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'with_photo' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'with_video' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'subtype' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'none',
              1 => 'top100',
              2 => 'bikini',
              ),
              'default' => 'none',
              'length' => '',
             ),
             'most_active_user' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'status_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'homepage' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'phone2' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'icq' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'msn' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'skype' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'zodiac' => 
             array(
              'type' => 'integer',
              'length' => '2',
             ),
             'partner_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'can_resive_gift' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'skan' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'rating' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'object_version' => 
             array(
              'notnull' => '',
              'default' => '1',
              'type' => 'string',
              'length' => '15',
             ),
             ), array(
             'indexes' => 
             array(
              'partner_id' => 
              array(
              'fields' => 
              array(
               0 => 'partner_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_profile_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_service', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'cost' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'comission' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'length' => '18',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'true',
              'length' => '25',
             ),
             'show_man' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'show_partner' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_settings', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'var_name' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'var_value' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'var_description' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_status_friend', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_testimonials', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'body' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_video', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'username' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'file_path' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'pub' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'size' => 
             array(
              'type' => 'integer',
              'length' => '11',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'format' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'is_convert' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'partner_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_forgot_password', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'unique_key' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'expires_at' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_group', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_group_permission', array(
             'group_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'permission_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'group_id',
              1 => 'permission_id',
             ),
             ));
        $this->createTable('sf_guard_permission', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '1000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_remember_key', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'remember_key' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'ip_address' => 
             array(
              'type' => 'string',
              'length' => '50',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'username' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'unique' => '1',
              'length' => '128',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'algorithm' => 
             array(
              'type' => 'string',
              'default' => 'sha1',
              'notnull' => '1',
              'length' => '128',
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'real_name' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '128',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'is_partner' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'partner_id' => 
             array(
              'type' => 'integer',
              'default' => '1',
              'length' => '8',
             ),
             'is_super_admin' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'last_login' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'pc' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'gender' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'm',
              1 => 'w',
              ),
              'default' => 'w',
              'length' => '',
             ),
             'culture' => 
             array(
              'type' => 'string',
              'length' => '2',
             ),
             'account' => 
             array(
              'type' => 'decimal',
              'scale' => '2',
              'default' => '0',
              'length' => '18',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'is_online' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'timer' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'email' => 
             array(
              'type' => 'string',
              'email' => '1',
              'notnull' => '1',
              'length' => '255',
             ),
             'is_agree' => 
             array(
              'type' => 'boolean',
              'default' => 'false',
              'length' => '25',
             ),
             'date_expire' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'is_active_idx' => 
              array(
              'fields' => 
              array(
               0 => 'is_active',
              ),
              ),
              'email' => 
              array(
              'fields' => 
              array(
               0 => 'email',
              ),
              ),
              'username' => 
              array(
              'fields' => 
              array(
               0 => 'username',
              ),
              ),
              'is_online' => 
              array(
              'fields' => 
              array(
               0 => 'is_online',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('sf_guard_user_group', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'group_id',
             ),
             ));
        $this->createTable('sf_guard_user_permission', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'permission_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'permission_id',
             ),
             ));
        $this->createTable('jo_faq_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('jo_news_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('jo_notify_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'icontent' => 
             array(
              'type' => 'string',
              'length' => '100000',
             ),
             'ititle' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('jo_page_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'icontent' => 
             array(
              'type' => 'string',
              'length' => '100000',
             ),
             'ititle' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('jo_profile_type_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('jo_service_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('jo_billing');
        $this->dropTable('jo_billing_type');
        $this->dropTable('jo_blacklist');
        $this->dropTable('jo_faq');
        $this->dropTable('jo_friend');
        $this->dropTable('jo_hotlist');
        $this->dropTable('jo_interest');
        $this->dropTable('jo_message');
        $this->dropTable('jo_news');
        $this->dropTable('jo_notify');
        $this->dropTable('jo_page');
        $this->dropTable('jo_payment');
        $this->dropTable('jo_photo');
        $this->dropTable('jo_profile');
        $this->dropTable('jo_profile_type');
        $this->dropTable('jo_service');
        $this->dropTable('jo_settings');
        $this->dropTable('jo_status_friend');
        $this->dropTable('jo_testimonials');
        $this->dropTable('jo_video');
        $this->dropTable('sf_guard_forgot_password');
        $this->dropTable('sf_guard_group');
        $this->dropTable('sf_guard_group_permission');
        $this->dropTable('sf_guard_permission');
        $this->dropTable('sf_guard_remember_key');
        $this->dropTable('sf_guard_user');
        $this->dropTable('sf_guard_user_group');
        $this->dropTable('sf_guard_user_permission');
        $this->dropTable('jo_faq_translation');
        $this->dropTable('jo_news_translation');
        $this->dropTable('jo_notify_translation');
        $this->dropTable('jo_page_translation');
        $this->dropTable('jo_profile_type_translation');
        $this->dropTable('jo_service_translation');
    }
}