<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('jo_profile_packet', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'cucssu' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('jo_profile_packet_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '250',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '2500',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->addColumn('jo_message', 'image', 'string', '250', array(
             ));
        $this->addColumn('jo_notify', 'file', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'hair_lenght', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'hair_color', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'eye_color', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'hobbies', 'string', '2500', array(
             ));
        $this->addColumn('jo_profile', 'weight', 'integer', '8', array(
             ));
        $this->addColumn('jo_profile', 'looking_for', 'string', '5', array(
             ));
        $this->addColumn('jo_profile', 'looking_for_role', 'string', '50', array(
             ));
        $this->addColumn('jo_profile', 'contact_lenses', 'boolean', '25', array(
             'default' => 'false',
             ));
        $this->addColumn('jo_profile', 'cred_num', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'cred_date', 'date', '25', array(
             ));
        $this->addColumn('jo_profile', 'cred_cvv', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'cred_person', 'string', '250', array(
             ));
        $this->addColumn('jo_profile', 'packet_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('jo_profile_packet');
        $this->dropTable('jo_profile_packet_translation');
        $this->removeColumn('jo_message', 'image');
        $this->removeColumn('jo_notify', 'file');
        $this->removeColumn('jo_profile', 'hair_lenght');
        $this->removeColumn('jo_profile', 'hair_color');
        $this->removeColumn('jo_profile', 'eye_color');
        $this->removeColumn('jo_profile', 'hobbies');
        $this->removeColumn('jo_profile', 'weight');
        $this->removeColumn('jo_profile', 'looking_for');
        $this->removeColumn('jo_profile', 'looking_for_role');
        $this->removeColumn('jo_profile', 'contact_lenses');
        $this->removeColumn('jo_profile', 'cred_num');
        $this->removeColumn('jo_profile', 'cred_date');
        $this->removeColumn('jo_profile', 'cred_cvv');
        $this->removeColumn('jo_profile', 'cred_person');
        $this->removeColumn('jo_profile', 'packet_id');
    }
}