// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Жирный (Ctrl+B)',
italic_desc : 'Наклонный (Ctrl+I)',
underline_desc : 'Подчеркнутый (Ctrl+U)',
striketrough_desc : 'Перечеркнутый',
justifyleft_desc : 'По левому краю',
justifycenter_desc : 'По центру',
justifyright_desc : 'По правому краю',
justifyfull_desc : 'По ширине',
bullist_desc : 'Маркированный список',
numlist_desc : 'Нумерованный список',
outdent_desc : 'Уменьшить отступ',
indent_desc : 'Увеличить отступ',
undo_desc : 'Отменить (Ctrl+Z)',
redo_desc : 'Повторить (Ctrl+Y)',
link_desc : 'Вставить/изменить ссылку',
unlink_desc : 'Удалить ссылку',
image_desc : 'Вставить/изменить изображение',
cleanup_desc : 'Подчистить код',
focus_alert : 'Фокус должен быть на редакторе перед использованием этой команды.',
edit_confirm : 'Вы хотите использовать режим WYSIWYG для этого текстового поля?',
insert_link_title : 'Вставить/изменить ссылку',
insert : 'Вставить',
update : 'Обновить',
cancel : 'Отмена',
insert_link_url : 'URL ссылки',
insert_link_target : 'Цель',
insert_link_target_same : 'Открывать ссылку в том же окне',
insert_link_target_blank : 'Открывать ссылку в новом окне',
insert_image_title : 'Вставить/изменить изображение',
insert_image_src : 'URL изображения',
insert_image_alt : 'Описание изображения',
help_desc : 'Помощь',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Копировать/Вырезать/Вставить не доступно в Mozilla м Firefox.\nВы хотите получить больше информации об этом?',
popup_blocked : 'Извините, но мы заметили что ваш popup-blocker отключил окно,  которое обеспечивает функциональность приложения. Вы должны отключить блокировку всплывающих окон для этого сайта чтобы использовать этот инструмент полнофункционально.'
});
