<?php

/**
 * BlacklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlacklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlacklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Blacklist');
    }
}