<?php

/**
 * HotlistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HotlistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HotlistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hotlist');
    }



}