<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageTable
     */

        public  function retrieveBackendMessageList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin($rootAlias . '.FromUser fu');
    $q->leftJoin($rootAlias .'.ToUser tu');
    return $q;
  }

    public static function getInstance()
    {
        return Doctrine_Core::getTable('Message');
    }

    public static function getCount($user)
    {
        $cnt = Doctrine::getTable('Message')
            ->createQuery('a')
            ->where('a.to_id=?',array($user->getId()))
            ->count();
        if($cnt>0)
        {
            return $cnt;
        }
        return '';
    }


     public static function getCountNew($user)
    {
         $cnt = Doctrine::getTable('Message')
         ->createQuery('a')
         ->where('a.to_id=? and a.is_read=? and a.type_message<>? and a.type_message<>?',array($user->getId(),false,'smile','first'))
         ->count();
         if($cnt>0)
         {
            return $cnt;
         }
         return '';
    }

    /// Непрочитанные первые письма
     public static function getCountNewFirst($user)
    {
         $cnt = Doctrine::getTable('Message')
         ->createQuery('a')
         ->where('a.to_id=? and a.is_read=? and a.type_message=?',array($user->getId(),false,'first'))
         ->count();
         if($cnt>0)
         {
            return '<span class="cnt_new">('.$cnt.')</span>';
         }
         return '';
    }

    /// Непрочитанные улыбки
     public static function getCountNewSmile($user)
    {
         $cnt = Doctrine::getTable('Message')
         ->createQuery('a')
         ->where('a.to_id=? and a.is_read=? and a.type_message=?',array($user->getId(),false,'smile'))
         ->count();
         if($cnt>0)
         {
            return '<span class="cnt_new">('.$cnt.')</span>';
         }
         return '';
    }

}