  giftbox_cost_transport: 10
  demo_account: true
  personal_mail: true
  one_language: false
  max_photo: 10
  max_video: 10
  big_photo_width: 333
  big_photo_height: 488
  reg_search: false
  reg_profile: true
  reg_real_gift: false
  reg_virtual_gift: false
  use_smile: true
  use_fav: true
  use_message: true
  use_black: true
  use_claim: true
  use_interest: true
  use_real_gift: true
  use_virtual_gift: true
  use_contact: true
  use_chat: true
  use_skan: true
  perpage_search: 9
  not_same_gender: true
  giftbox_payment: true
  giftbox_additional_type: true
  giftbox_all: false
  giftbox_category_all: false
  cost_virtual_gift: false
  sf_guard_plugin_success_signin_url: profile/show
  email_admin: zdimon77@gmail.com
  limit_fletter: 3
  chat_version: symfony
  show_translation: true
  procent_transport_comission: 50
  auto_login: true
  use_abonement: true
  small_photo_width: 70
  small_photo_eight: 70
  middle_photo_width: 96
  middle_photo_height: 138
  site_name: our-feeling.leworm.fr
  email_reply: info@our-feeling.com
  #paypal_email: jb1008@wanadoo.fr
  paypal_email: jo39400@gmail.com
