# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        '<?php echo sfConfig::get('app_meta_title') ?>'
    description:  '<?php echo sfConfig::get('app_meta_keyword') ?>'
    keywords:     '<?php echo sfConfig::get('app_meta_description') ?>'
    language:     en
    #robots:       index, follow
  javascripts:
    - /js/jquery-1.5.1.min.js
    - /js/jquery.easing.min.1.3.js
    - /js/fancybox/jquery.fancybox-1.3.4.pack.js
    - /js/jquery.jcarousel.min.js
    - /js/jquery.colorbox-min.js
    - /js/liValidForm.v2.js
    - /js/main.js
    - /js/plugins.js
    - /js/jquery-ui-1.8.14.custom.min.js
    - /js/fancybox/jquery.fancybox-1.3.4.pack.js
    - /js/jquery.LiVMenu.js

  stylesheets:
    - style.css
    - colorbox.css
    - /css/themes/aristo/jquery-ui-1.8.16.custom.css
    - liValidForm.css
    - liVMenu.css
    - skin.css
    - /js/fancybox/jquery.fancybox-1.3.4.css

  has_layout:     true
  layout:         layout
