generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Actions
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          actions
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [type_keywords, description, user, created_at]
        sort: [id, DESC]
      filter:  
        display: [created_at, type_actions_id]
      form:    ~
      edit:    ~
      new:     ~
