generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Liqpay
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          liqpay
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, user_id, created_at, status]
      filter:  
        display: [status, created_at]
      form:    ~
      edit:    ~
      new:     ~
