generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ScamerReport
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scamer_report
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [content, user, scamer, _check]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
