generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BillingType
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          billing_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [title, summa]
      filter:  ~
      form:    ~
      edit:    
        display: [title, summa]
      new:     ~
