generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProfilePacket
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profile_packet
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Membership
        display: [id, _name, _descr]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
