generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MyCity
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          my_city
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        pub:
          label: Approve?
      list:    
        title: My place
        display: [country, city, pub]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
