generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Chat2Room
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          chat2_room_chat_room
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, date_start, caller, answer, status]
        object_actions:
          _show: ~
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [date_start, _chanels, _abonents, _messages]
