

#  настройки сайта ##########################
Settings:
  tableName: jo_settings
  columns:
    var_name: string(250)
    var_value: string(250)
    var_description: string(250)
    pub:
      type: boolean
      default: false

#  Профайл пользователя ##########################
Profile:
  tableName: jo_profile
  actAs:
    Timestampable: ~
    Cachetaggable: ~
  columns:
    user_id: integer
    first_name: string(255)
    last_name: string(255)
    middle_name: string(255)
    real_name: string(255)
    gender: 
      type: enum
      values: [m, w]
      default: w
    city:   string(250)
    country: string(2)
    zip: string(20)
    adress: string(250)
    phone:  string(250)
    birthday: date
    height: string(250)
    body_type: string(250)
    relationship: string(250)
    rost: string(250)
    ves:  string(250)
    ethnicity: string(50)
    religion:  string(100)
    marital_status: string(50)
    children: string(250)
    where_children: string(250)
    want_children: string(250)
    im: string(250)
    occupation: string(250)
    language1: string(50)
    language_skill1: string(250)
    language2: string(50)
    language_skill2: string(250)
    language3: string(50)
    language_skill3: string(250)
    education: string(100)
    income: string(250)
    smoker: string(250)
    drinker: string(250)
    headline: string(250)
    description: string(25000)
    i_can_receive: string(250)
    i_look_for_a: string(250)
    looking_for_age_from: integer
    looking_for_age_to:   integer
    looking_for_a_height_from: string(250)
    looking_for_a_height_to: string(250)
    looking_for_a_body_type_from: string(250)
    looking_for_a_body_type_to: string(250)
    relationship: string(250)
    ideal_match_description: string(2500)
    notify_me_about_news:
      type: boolean
      default: true
    mobile_phone: string(250)
    photo: string(250)
    hair_lenght: string(250)
    hair_color: string(250)
    eye_color: string(250)
    hobbies: string(2500)
    weight: integer
    looking_for: string(5)
    looking_for_role: string(50)
    contact_lenses:
      type: boolean
      default: false
    cred_num: string(250)
    cred_date: date
    cred_cvv: string(250)
    cred_person: string(250)
    is_active:
      type: boolean
      default: false
    is_new_message:
      type: boolean
      default: false
    is_new_friend:
      type: boolean
      default: false	
    is_new_request:
      type: boolean
      default: false
    is_new_gift:
      type: boolean
      default: false
    is_new_hotlist:
      type: boolean
      default: false	 
    is_empty:
      type: boolean
      default: true
    is_online:
      type: boolean
      default: false
    with_photo:
      type: boolean
      default: false
    with_video:
      type: boolean
      default: false
    subtype:
      type: enum
      values: [none, top100, bikini]
      default: none
    most_active_user: integer
    status_id: integer(4)
    homepage: string(250)
    phone2: string(250)
    icq: string(250)
    msn: string(250)
    skype: string(250)
    zodiac: integer(2)
    partner_id: integer(4)
    can_resive_gift:
      type: boolean
      default: false
    skan: string(250)
    rating: integer(4)
    packet_id: integer
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
      type: one
      foreignType: one
    Status:
      local: status_id
      onDelete: CASCADE
      foreign:  id
      class: ProfileType
    Packet:
      local: packet_id
      onDelete: CASCADE
      foreign:  id
      class: ProfilePacket
  indexes:
    partner_id:
      fields: [partner_id]

# Статусы анкет   ##########################

ProfileType:
  tableName: jo_profile_type
  actAs:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:  string(250)
    description:  string(2500)

# Пакеты   ##########################

ProfilePacket:
  tableName: jo_profile_packet
  actAs:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:  string(250)
    description:  string(2500)
    cucssu: string(2500)




#  Фото ##########################
Photo:
  tableName: jo_photo
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id: integer
    username: string(50)
    title:
      type: string(50)
    image:
      type: string(250)
    pub:
      type: boolean
      default: false
    is_main:
      type: boolean
      default: false
    is_private:
      type: boolean
      default: false 
    size: integer(11)
    partner_id: integer
  relations:
    User:
      local: user_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser
    Partner:
      local: partner_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser


#  Видео ##########################
Video:
  tableName: jo_video
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id: integer
    username: string(50)
    title:
      type: string(50)
    file_path:
      type: string(250)
    pub:
      type: boolean
      default: false
    size: integer(11)
    description: string(250)
    format: string(50)
    is_convert:
      type: boolean
      default: false
    partner_id: integer
  relations:
    User:
      local: user_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser
    Partner:
      local: partner_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser      

#  Сообщения ##########################
Message:
  tableName: jo_message
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    from_id: integer
    from_username: string(50)
    to_id: integer
    to_username: string(50)
    from_partner_id: integer
    to_partner_id: integer
    title: string(100)
    content: string(2500)
    translate: string(2500)
    image: string(250)
    reply_id: integer(4)
    type_message:
      type: enum
      values: [smile, message, first]
      default: message
    pub:
      type: boolean
      default: true
    is_read:
      type: boolean
      default: false
    is_reply:
      type: boolean
      default: false
    del_from:
      type: boolean
      default: false
    del_to:
      type: boolean
      default: false
  relations:
    FromUser:
      local: from_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser
    ToUser:
      local: to_id
      onDelete: CASCADE
      foreign:  id
      class: sfGuardUser
  indexes:
    to_username:
      fields: [to_username]
    from_username:
      fields: [from_username]
    reply_id:
      fields: [reply_id]
    type_message:
      fields: [type_message]

#  друзья ##########################
Friend:
  tableName: jo_friend
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id: integer
    friend_id: integer
    status_id: integer(4)
    del_user:
      type: boolean
      default: false
    del_friend:
      type: boolean
      default: false 
    is_read_user:
      type: boolean
      default: false
    is_read_friend:
      type: boolean
      default: false
    contact: string(10000) 
    from_partner_id: integer
    to_partner_id: integer
    request_video:
      type: boolean
      default: false
    accept_video:
      type: boolean
      default: false
    read_accept:
      type: boolean
      default: false   
  relations:
    User:
      local: user_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Friend:
      local: friend_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Status:
      local: status_id
      foreign: id
      onDelete: CASCADE
      class: StatusFriend      
  indexes:
    is_read_user:
      fields: [is_read_user]
    is_read_friend:
      fields: [is_read_friend]

#  статусы друзей ##########################      
StatusFriend:
  tableName: jo_status_friend
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title: string(100)



      
#  Страницы ##########################
Page:
  tableName: jo_page
  actAs:
    I18n:
      fields: [icontent, ititle]  
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true  
    alias: 
      type: string(250)  
    title: 
      type: string(250) 
    icontent: 
      type: string(100000) 
    ititle: 
      type: string(250)
    undel:
      type: boolean
      default: false

#  Отзывы  ##########################
Testimonials:
  tableName: jo_testimonials
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    body:  string(2500)
    image:  string(250)
    name:  string(250)
    pub:
      type: boolean
      default: false

#  Услуги ##########################
Service:
  tableName: jo_service
  actAs:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(250)
    description:   string(2500)
    cost:
      type: decimal
      scale: 2
    comission:
      type: decimal
      scale: 2
    pub:
      type: boolean
      default: true
    show_man:
      type: boolean
      default: false
    show_partner:
      type: boolean
      default: false 
  
#  Уведомления ##########################
Notify:
  tableName: jo_notify
  actAs:
    I18n:
      fields: [icontent, ititle]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(250)
    icontent:
      type: string(100000)
    ititle:
      type: string(250)
    file:
      type: string(250)

#  Новости   ##########################
News:
  tableName: jo_news
  actAs:
    Timestampable:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:  string(250)
    description:   string(2500)
    image:  string(250)
    pub:
      type: boolean
      default: false

#  Faq   ##########################
Faq:
  tableName: jo_faq
  actAs:
    Timestampable:
    I18n:
      fields: [title, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:  string(250)
    description:   string(2500)
    pub:
      type: boolean
      default: false

#  Платежи ##########################
Payment:
  tableName: jo_payment
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    service_id: integer(4)
    user_id:  integer
    woman_id:  integer
    username:  string(50)
    partner_id: integer
    room_id: integer
    summa:
      type: decimal
      scale: 2
    balanse:
      type: decimal
      scale: 2
    comission:
      type: decimal
      scale: 2
    title:
      type: string(250)
    description:   string(2500)
    cost:
      type: decimal
      scale: 2
    is_closed:
      type: boolean
      default: true
  relations:
    User:
      local: user_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Partner:
      local: partner_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Woman:
      local: woman_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Service:
      local: service_id
      foreign: id
      onDelete: CASCADE
      class: Service    

#  Хотлист  ##########################
Hotlist:
  tableName: jo_hotlist
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    from_id:  integer
    to_id:  integer
    last_message_id: integer(4)
    is_new_message:
      type: boolean
      default: false
    is_opened:
      type: boolean
      default: false
  relations:
    FromUser:
      local: from_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    ToUser:
      local: to_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    LastMessage:
      local: last_message_id
      foreign: id
      onDelete: CASCADE
      class: Message

#  Черный список  ##########################
Blacklist:
  tableName: jo_blacklist
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:  integer
    black_id:  integer
  relations:
    User:
      local: user_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Black:
      local: black_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser

# Типы пополнений   ##########################

BillingType:
  tableName: jo_billing_type
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:  string(250)
    code:  string(250)
    summa:  integer(4)
    credit:  integer(4)

#  Билинг  ##########################
Billing:
  tableName: jo_billing
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(250)
    summa:
      type: decimal
      scale: 2
    balance:
      type: decimal
      scale: 2
    credit: integer(4)
    user_id:  integer
    username:  string(50)
    type_id: integer(4)
  relations:
    User:
      local: user_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    BillingType:
      local: type_id
      foreign: id
      onDelete: CASCADE
      class: BillingType

#  Просмотр профайла  ##########################
Interest:
  tableName: jo_interest
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:  integer
    interest_id:  integer
    is_read_user:
      type: boolean
      default: false
    is_read_interest:
      type: boolean
      default: false
  relations:
    User:
      local: user_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser
    Interest:
      local: interest_id
      foreign: id
      onDelete: CASCADE
      class: sfGuardUser